'use client'; // This layout uses client-side hooks and event listeners

import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';

// Include imports for Lenis AND the cursor
import React, { useEffect, useRef, useState } from 'react';
import Lenis from '@studio-freight/lenis';
import { motion, useMotionValue, useSpring } from 'framer-motion';
import Image from 'next/image';
import Dock from '@/blocks/Components/Dock/Dock';
import Link from 'next/link';

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { gilroy } from '@/fonts/fonts';
import {
  NAV_ITEMS,
  SOCIAL_LINKS,
  CURSOR_CONFIG,
  SPRING_CONFIG,
  LENIS_CONFIG,
  RESPONSIVE,
  SPACING,
  ICON_SIZES,
  DOCK_CONFIG,
  SOCIAL_CONTAINER,
  Z_INDEX,
} from './config';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Metadata is for server components, so it stays outside the client component export
// It should ideally be in a separate metadata.ts file in App Router client components
// Keeping it commented out as in your provided code.
/*
  // app/metadata.ts
  import type { Metadata } from 'next';

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const lenis = useRef<Lenis | null>(null);

  useEffect(() => {
    // Initialize Lenis only in the browser environment
    if (typeof window !== 'undefined') {
      lenis.current = new Lenis(LENIS_CONFIG);

      // This function updates Lenis on each frame using requestAnimationFrame
      function raf(time: number) {
        lenis.current?.raf(time);
        requestAnimationFrame(raf);
      }

      // Start the animation loop
      requestAnimationFrame(raf);

      // Clean up the Lenis instance when the component unmounts
      return () => {
        lenis.current?.destroy();
      };
    }
  }, []); // Empty dependency array ensures this effect runs only once on mount and cleans up on unmount
  // --- Custom Cursor Implementation ---
  const cursorX = useMotionValue(0);
  const cursorY = useMotionValue(0);

  const dotX = useSpring(cursorX, SPRING_CONFIG.DOT);
  const dotY = useSpring(cursorY, SPRING_CONFIG.DOT);

  const outlineX = useSpring(dotX, SPRING_CONFIG.OUTLINE);
  const outlineY = useSpring(dotY, SPRING_CONFIG.OUTLINE);

  useEffect(() => {
    const moveCursor = (e: MouseEvent) => {
      cursorX.set(e.clientX);
      cursorY.set(e.clientY);
    };

    setTimeout(() => {
      cursorX.set(window.innerWidth / 2);
      cursorY.set(window.innerHeight / 2);
    }, 0);

    // Add event listener for subsequent mouse movements
    window.addEventListener('mousemove', moveCursor);

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('mousemove', moveCursor);
    };
  }, [cursorX, cursorY]); // Dependencies: update effect if motion values change (they won't here, but good practice)
  // --- End Custom Cursor Implementation ---

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gilroy.variable} select-none bg-black font-gilroy antialiased`}
        style={{ cursor: 'none' }}
      >
        {/* Custom Cursor Dot */}
        <motion.div
          style={{
            x: dotX,
            y: dotY,
            pointerEvents: 'none',
            left: 0,
            top: 0,
            position: 'fixed',
            zIndex: Z_INDEX.CURSOR_DOT,
            transform: 'translate(-50%, -50%)',
            width: `${CURSOR_CONFIG.DOT.size}px`,
            height: `${CURSOR_CONFIG.DOT.size}px`,
            borderRadius: '50%',
            backgroundColor: CURSOR_CONFIG.DOT.color,
            boxShadow: `0 0 ${CURSOR_CONFIG.DOT.glowSize}px ${CURSOR_CONFIG.DOT.glowSpread}px ${CURSOR_CONFIG.DOT.glowColor}`,
          }}
          className={RESPONSIVE.HIDDEN_MOBILE}
        />
        {/* Custom Cursor Outline */}
        <motion.div
          style={{
            x: outlineX,
            y: outlineY,
            pointerEvents: 'none',
            left: 0,
            top: 0,
            position: 'fixed',
            zIndex: Z_INDEX.CURSOR_OUTLINE,
            transform: 'translate(-50%, -50%)',
            width: `${CURSOR_CONFIG.OUTLINE.size}px`,
            height: `${CURSOR_CONFIG.OUTLINE.size}px`,
            borderRadius: '50%',
            border: `${CURSOR_CONFIG.OUTLINE.borderWidth}px solid ${CURSOR_CONFIG.OUTLINE.borderColor}`,
            opacity: CURSOR_CONFIG.OUTLINE.opacity,
          }}
          className={RESPONSIVE.HIDDEN_MOBILE}
        />
        <header
          className={`sticky top-0 z-50 flex w-full items-center justify-between bg-transparent backdrop-blur-[3px] ${SPACING.HEADER_PADDING}`}
        >
          <Link href="/" passHref>
            <Image
              src="/logo/logo.png"
              alt="D Logo"
              width={35}
              height={35}
              className="hover:rotate-10 m-4 transition-all duration-300 hover:scale-150 hover:brightness-125 md:m-10"
            />
          </Link>

          {/* Hamburger button - visible only on small screens */}
          <button
            className="p-2 text-white focus:outline-none md:hidden"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle mobile menu"
          >
            <div className="mb-1.5 h-0.5 w-6 bg-white transition-all duration-300 ease-in-out"></div>
            <div className="mb-1.5 h-0.5 w-6 bg-white transition-all duration-300 ease-in-out"></div>
            <div className="h-0.5 w-6 bg-white transition-all duration-300 ease-in-out"></div>
          </button>
        </header>
        {mobileMenuOpen && (
          <div className="h-[calc(100vh - 72px)] sm:h-[calc(100vh - 80px)] md:h-[calc(100vh - 96px)] fixed left-0 right-0 top-[72px] z-40 overflow-y-auto bg-transparent p-4 pt-10 backdrop-blur-[10px] sm:top-[80px] sm:p-5 md:top-[96px] md:hidden">
            {' '}
            <nav className="flex flex-col space-y-4">
              {NAV_ITEMS.map((item, index) => (
                <Link
                  key={index}
                  href={item.href}
                  className="px-4 py-2 text-base font-medium text-white hover:text-gray-300 sm:text-lg"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </div>
        )}
        {children}{' '}
        {/* This is where your page content (like page.tsx) will be rendered */}
        <div className={`fixed bottom-6 left-1/2 z-50 -translate-x-1/2`}>
          <Dock
            items={NAV_ITEMS as any}
            panelHeight={DOCK_CONFIG.panelHeight}
            baseItemSize={DOCK_CONFIG.baseItemSize}
            magnification={DOCK_CONFIG.magnification}
          />
        </div>
        <div
          className={`fixed bottom-4 right-4 z-50 md:bottom-8 md:right-8 ${SOCIAL_CONTAINER.backdrop} ${SOCIAL_CONTAINER.border} ${SOCIAL_CONTAINER.rounded} ${SPACING.SOCIAL_PADDING} flex flex-col items-center ${SPACING.SOCIAL_SPACE}`}
        >
          {SOCIAL_LINKS.map((link) => (
            <Link
              key={link.platform}
              href={link.href}
              target="_blank"
              rel="noopener noreferrer"
              className="transition-transform duration-200 hover:scale-110"
            >
              <Image
                src={link.iconPath}
                alt={`${link.platform} icon`}
                width={20}
                height={20}
                className={`${ICON_SIZES.SOCIAL.width} ${ICON_SIZES.SOCIAL.height} object-contain`}
              />
            </Link>
          ))}
        </div>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
